#!/bin/bash 
#SBATCH -J PDMD 
#SBATCH -o test.out
#SBATCH -e test.err
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --mem=0
#SBATCH -p gh-dev 
#SBATCH -t 02:00:00

module purge
module reset
module load gcc/14.2.0
module load cuda/12.8
module load nccl/2.19.3
module load openmpi/5.0.5
module load python3_mpi/3.11.8

source $SCRATCH/pdmdenv/bin/activate

srun python3 run.py --train   
